//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paint {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class i18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal i18n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paint.i18n", typeof(i18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ellipse.
        /// </summary>
        internal static string ellipse {
            get {
                return ResourceManager.GetString("ellipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string history {
            get {
                return ResourceManager.GetString("history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pen.
        /// </summary>
        internal static string pen {
            get {
                return ResourceManager.GetString("pen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rectangle.
        /// </summary>
        internal static string rect {
            get {
                return ResourceManager.GetString("rect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redo.
        /// </summary>
        internal static string redo {
            get {
                return ResourceManager.GetString("redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to segment.
        /// </summary>
        internal static string segment {
            get {
                return ResourceManager.GetString("segment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shapes.
        /// </summary>
        internal static string shapes {
            get {
                return ResourceManager.GetString("shapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undo.
        /// </summary>
        internal static string undo {
            get {
                return ResourceManager.GetString("undo", resourceCulture);
            }
        }
    }
}
